#!/usr/bin/env ruby
require 'json'

once = ARGV.first == "--once"

REQURED_LENGTH = 16*1024

message = ('aaa'..'bzz').each_with_object({ message: 'Log text' }) do |key, hash|
  hash[key] = "#{key}_value"
end

message = JSON.generate(message)

raise 'Message is too short, you need to make it longer to trigger the splitting' if message.length < REQURED_LENGTH

begin
  # Print a JSONLine message every second.
  loop do
    puts message
    sleep 1
    exit 0 if once
  end
rescue Interrupt
  # Exit successfully on Ctrl+C.
  exit 0
end
